config/routes.rb
Rails.application.routes.draw do
  root to: 'homepages#index'

  get '/entry', to: 'homepages#entry', as: :entry
  get '/users/:id', to: 'users#show', as: :user

  post '/create_entry', to: 'users#create', as: :create_entry
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/choice.rb
class Choice < ActiveRecord::Base
  belongs_to :prop
end

app/models/prop.rb
class Prop < ActiveRecord::Base
  has_many :user_props
  has_many :users, through: :props
  has_many :choices
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :user_choices
  has_many :choices, through: :user_choices

  validates :name, uniqueness: true

  def score
    choices.where(correct: true).try(:count)
  end

  def prop_pick(prop)
    prop.choices.select { |c| c.id.in?(choice_ids) }.try(:first)
  end

  def choices_ids
    choices.pluck(:id)
  end
end

app/models/user_choice.rb
class UserChoice < ActiveRecord::Base
  belongs_to :user
  belongs_to :choice
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/homepages_controller.rb
class HomepagesController < ActionController::Base
  def index
    @users = User.all
    render :index
  end

  def entry
    @props = Prop.all
    render 'entry'
  end
end

app/controllers/users_controller.rb
class UsersController < ActionController::Base
  def create
    user = User.create(name: params[:name])

    params["prop"].each_value do |choice|
      user.user_choices.create(choice_id: choice.to_i)
    end

    redirect_to root_path
  end

  def show
    @props = Prop.all
    @user = User.find params[:id]
    render :show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/homepages/entry.html.erb
<div class="top">
  <h1 class="title"><%= link_to "Lit AF Super Bowl Prop Bets", root_path %></h1>
</div>

<div class="heading">
  <h2>Make Your Picks</h2>
</div>


<%= form_tag("/create_entry", method: "post") do %>
  <%= label_tag(:name) %>
  <%= text_field_tag(:name) %>

  <% @props.each do |prop| %>
    <ul>
      <p><%= prop.description %> </p>
      <% prop.choices.each do |choice| %>
        <%= radio_button_tag("[prop]#{prop.id}", choice.id) %>
        <%= label_tag(prop.id, choice.description) %>
      <% end %>
    </ul>
  <% end %>

  <input class="button-primary" type="submit" value="Submit">
<% end %>

app/views/homepages/index.html.erb
<div class="top">
  <h1 class="title">Lit AF Super Bowl Prop Bets</h1>
</div>

<div class="links">
  <h2><%= link_to "Create Your Entry", entry_path %></h2>
</div>

<div class="entries">
  <h2>View Entries</h2>
  <% @users.each do |user| %>
    <h3><%= link_to user.name, user_path(user) %> - Score: <%= user.score %></h3>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SuperBowlProps</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<div class="top">
  <h1 class="title"><%= link_to "Lit AF Super Bowl Prop Bets", root_path %></h1>
</div>

<h2><%= @user.name %> Score: <%= @user.score %></h2>
<% @props.each do |prop| %>
  <p><%= prop.description %> - Your pick: <%= @user.prop_pick(prop).try(:description) %></p>
<% end %>